ERROR - 2021-12-03 12:21:45 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-12-03 12:21:45 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1527): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#2 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\Model.php(509): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#3 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\BaseModel.php(1084): CodeIgniter\Model->countAllResults(false)
#4 C:\Users\yerob\xampp\htdocs\ci4login\app\Controllers\Home.php(20): CodeIgniter\BaseModel->paginate(6, 'ebook')
#5 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\CodeIgniter.php(824): App\Controllers\Home->index()
#6 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\Users\yerob\xampp\htdocs\ci4login\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\yerob\\...')
#10 {main}
CRITICAL - 2021-12-03 12:21:45 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\Users\yerob\xampp\htdocs\ci4login\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\Users\\yerob\\...', 96, Array)
#1 C:\Users\yerob\xampp\htdocs\ci4login\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Home), true)
#2 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\Debug\Exceptions.php(229): include('C:\\Users\\yerob\\...')
#3 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\Users\yerob\xampp\htdocs\ci4login\vendor\codeigniter4\framework\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
